### ISSUE TITLE
how to make preview from twitter post?

### ISSUE THREAD

**Issue by MINIMALaq** [meyt/linkpreview#9]
I want to create a preview from a twitter link like [this](https://twitter.com/CSProfKGD/status/1440386526630744073) but it gave me this 
```
error:
title: JavaScript is not available.
description: We’ve detected that JavaScript is disabled in this browser. Please enable JavaScript or switch to a supported browser to continue using twitter.com. You can see a list of supported browsers in our Help Center.
image: None
force_title: JavaScript is not available.
absolute_image: None
```
How to use this library for twitter?

**Comment by meyt** [comment]
Hi @MINIMALaq, you need to just set a crawler UserAgent like this:

```python
from linkpreview import Link, LinkPreview, LinkGrabber

headers = {'User-Agent': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'}
url = "https://twitter.com/CSProfKGD/status/1440386526630744073"
grabber = LinkGrabber()
content, url = grabber.get_content(url, headers=headers)
link = Link(url, content)
preview = LinkPreview(link)

print('\n'.join([
    "%s: %s" % (k, getattr(preview, k))
    for k in ('title', 'description', 'image', 'force_title', 'absolute_image')
]))
```

Output:
```yaml
title: Kosta Derpanis on Twitter
description: “Tools to Design or Visualize Architecture of Neural Network

https://t.co/8rzEF4ght6”
image: https://pbs.twimg.com/media/E_1Hsf5UUAItlnS.jpg:large
force_title: Kosta Derpanis on Twitter
absolute_image: https://pbs.twimg.com/media/E_1Hsf5UUAItlnS.jpg:large
```
